import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

const translations = {
  ar: {
    dashboardTitle: "غرفة العمليات السرية (Dashboard) 🔐",
    liveTracking: "الرادار والمتابعة اللحظية",
    liveTrackingDesc: "راقب تقدم الملكة في الموقع لحظة بلحظة وأرسل لها همسات وإشعارات فورية تظهر على شاشتها.",
    settingsTitle: "إعدادات التجربة والمحتوى",
    settingsDesc: "خصص الرسائل، الأسئلة، والمحكمة لإنشاء تجربة مصالحة سينمائية تليق بها.",
    saveChanges: "حفظ التعديلات السحرية ✨",
    saving: "جاري حفظ السحر...",
    dangerZone: "منطقة الخطر (Danger Zone)",
    dangerZoneDesc: "إنهاء الجلسة سيؤدي إلى تدمير الرابط وحذف جميع بيانات المحكمة والذكريات نهائياً.",
    deleteSiteBtn: "تدمير الرابط وإنهاء الجلسة نهائياً 🗑️",
    sendBtn: "إرسال فوراً ⚡",
    sending: "جاري الإرسال...",
    refresh: "تحديث الرادار 🔄",
    noVisits: "الرادار هادئ.. لا توجد زيارات حتى الآن 📡",
    noVisitsDesc: "بمجرد أن تفتح الملكة الرابط السري، ستظهر إحداثيات شاشتها وتحركاتها هنا مباشرة.",
    landingSubtitle: "المنصة السينمائية الأولى لإنشاء روابط مصالحة تفاعلية تذيب الخلافات بأسلوب ذكي ومبهج.",
    createMagicLink: "اصنع رابط المصالحة السحري الآن 🪄",
    creating: "جاري نسج المفاجأة...",
    magicLinkReady: "✨ المفاجأة جاهزة كالصاروخ! انسخ الرابط السري وشاركه مع الملكة الآن:",
    copyLink: "نسخ الرابط السري 📋",
    copied: "تم النسخ بنجاح! 🚀",
    createLinkError: "تعذر إنشاء الرابط، يرجى المحاولة مرة أخرى.",
    boyNameLabel: "اسمك إنت (البطل)",
    girlNameLabel: "اسم الملكة (شريكتك)",
    petNameLabel: "اسم الدلع المفضل لها",
    boyNamePlaceholder: "مثال: أحمد / كريم...",
    girlNamePlaceholder: "مثال: مريم / نور...",
    petNamePlaceholder: "مثال: مريومة / نوني...",
    customSlugLabel: "الرابط المخصص الخاص بكم",
    customSlugPlaceholder: "ahmed-mariam",
    creatorEmailLabel: "بريدك الإلكتروني (لاستلام تقرير الصلح والإيميل السنوي)",
    creatorEmailPlaceholder: "vip@example.com",
    pwdLabel: "الرقم السري لفتح الرابط (مهم جداً)",
    pwdPlaceholder: "اكتب رقماً سرياً مميزاً...",
    pwdHintLabel: "تلميح الرقم السري (Hint)",
    pwdHintPlaceholder: "مثال: تاريخ أول مقابلة / مكان ديتنا المفضل...",
    trustText: "مضمون 100% | آمن وسري تماماً | مجاني للتجربة",
    privacyNote: "🛡️ نحن لا نطلب أي كلمات مرور لشبكات التواصل الاجتماعي أو تفاصيل مالية إطلاقاً.",
    basicSettings: "الأساسيات والنصوص",
    quizSettings: "الأسئلة والاختبار",
    courtSettings: "المحكمة والتقييم",
    letterSettings: "الجواب والهدايا",
    timeline: "ذكرياتنا (Timeline)",
    addMemory: "إضافة ذكرى جديدة",
    trivia: "اختبار الذاكرة (Trivia)",
    addQuestion: "إضافة سؤال فخ",
    coupons: "كروت الهدايا (Gift Coupons)",
    addCoupon: "إضافة كارت هدية",
    letterBody: "نص الجواب فقرة بفقرة",
    addParagraph: "إضافة فقرة عاطفية",
    pwdReminder: "⚠️ لا تنسَ إرسال الرقم السري (Password) للملكة لتتمكن من الدخول!",
    telegramAlerts: "الإشعارات (Telegram)",
    notificationsSettings: "إعدادات الرادار وإشعارات التليجرام",
    telegramSetup: "خطوات ربط إشعارات التليجرام الفورية:",
    telegramStep1: "1. ابحث عن البوت الرسمي",
    telegramStep2: "2. أرسل له الأمر /start",
    telegramStep3: "3. انسخ رقم الـ ID الخاص بك وضعه هنا",
    telegramOptional: "🔔 تفعيل إشعارات التليجرام الفورية (اختياري)",
    telegramChatIdPlaceholder: "Telegram Chat ID (e.g. 123456789)",
    aiGenerator: "المولد الذكي AI",
    aiTitle: "الصياغة السحرية بالذكاء الاصطناعي",
    aiDesc: "اكتب سبب الزعل واضغط توليد — سيصيغ الـ AI اعتذاراً رومانسياً متكاملاً مع أسئلة وفخوخ مخصصة.",
    coreIntent: "الهدف الأساسي (Core Intent)",
    textVibe: "روح النص (Vibe)",
    vibeIntensity: "جرعة المشاعر (Intensity)",
    incidentReasonPlaceholder: "مثال: نسيت عيد ميلادها / اتأخرت عليها في الخروجة...",
    generateMagic: "توليد سحري ✨",
    journeyMap: "خريطة الرحلة",
    currentSectionLabel: "المحطة الحالية",
    lastActionLabel: "آخر تفاعل",
    deleteSession: "إنهاء الجلسة",
    onlineNow: "متصلة الآن 🟢",
    offline: "لا توجد زيارات نشطة",
    atGate: "تفك تشفير البوابة 🔒",
    insidePlatform: "داخل المنصة التفاعلية 👑",
    disconnected: "غير متصلة ⚪",
    broadcastPlaceholder: "اكتب رسالة تظهر على شاشتها فوراً كهمس سري...",
    navWall: "جدار الاعتذارات 🔒",
    navStories: "معرض القصص 🏆",
    navGifts: "مولد الهدايا 🎁",
    navCreate: "إنشاء رابط مصالحة 🪄",
    navBlog: "المدونة 📚",
    demoBtn: "جرب في 10 ثوانٍ ⚡",
    loginBtn: "دخول الرادار 🔐",
    statsTitle: "عدد علاقات الحب التي تم إنقاذها وصالحها السيستم:",
    liveBadge: "مباشر الآن",
    adblockText: "نقدم منصة Safi.io مجاناً.. يرجى تعطيل مانع الإعلانات لدعمنا في الاستمرار 🤍",
    wallTitle: "جدار الاعتذارات السري المجهول 🔒",
    wallSubtitle: "مكان آمن ومحمي بنسبة 100% لنشر رسالة اعتذار مجهولة. الفضفضة هنا تريح القلب وتوصل رسالتك للعلن دون الكشف عن هويتك.",
    wallInputPlaceholder: "اكتب اعتذارك الصادق من القلب هنا (بحد أقصى 300 حرف)...",
    wallSubmitBtn: "انشر اعتذارك 🔒",
    wallEmpty: "كن أول من ينشر اعتذاراً صادقاً على الجدار...",
    wallSuccessMsg: "تم تعليق اعتذارك على الجدار بنجاح! ✨",
    storiesTitle: "معرض قصص اعتذار مضحكة وذكية 🏆",
    storiesSubtitle: "أغرب وأذكى مواقف الخناقات والمصالحة بين الكابلز. استمتع بقراءة القصص وامنح صوتك لأكثر قصة تستحق الفوز في مسابقة هذا الأسبوع!",
    voteBtn: "تصويت",
    votedBtn: "تم التصويت",
    storiesPromptTitle: "عندك قصة صلح ذكية أو خناقة طريفة؟ 💌",
    storiesPromptSubtitle: "أرسل قصتك لصفحتنا الرسمية وسنقوم بنشرها في مسابقة الأسبوع القادم لتربح كود هدية VIP!",
    giftsTitle: "مولد أفكار الهدايا الرومانسية السريعة 🎁",
    giftsSubtitle: "احصل على أفكار هدايا ذكية، غير تقليدية، ومصممة نفسياً وفلكياً حسب البرج الفلكي والفئة العمرية لشريكتك لضمان مصالحتها وإسعادها من أول محاولة!",
    giftsAgeLabel: "حدد الفئة العمرية للملكة",
    giftsZodiacLabel: "حدد برجها الفلكي (Zodiac)",
    giftsGenerateBtn: "توليد أفكار الهدايا السحرية الآن ✨",
    giftsSuggestedTitle: "💡 التوليفة السحرية الموصى بها لبرج",
    giftsCallToAction: "اصنع لها موقع اعتذار تفاعلي الآن واضمن رضاها 🪄",
    loginModalTitle: "دخول الرادار وغرفة العمليات 🕵️",
    loginModalSubtitle: "أدخل رابط الصفحة والرقم السري لمراقبة تحركاتها في الموقع لايف أو تعديل الأسئلة.",
    loginSlugLabel: "رابط الصفحة (Slug)",
    loginPwdLabel: "الرقم السري للإدارة",
    loginSubmitBtn: "تشغيل الرادار السري 🚀",
    loginErrorInvalid: "رابط الصفحة أو الرقم السري غير صحيح",
    loginErrorNetwork: "فشل الاتصال بالخادم، يرجى المحاولة مرة أخرى.",
    footerPrivacy: "سياسة الخصوصية",
    footerTerms: "شروط الاستخدام",
    footerContact: "اتصل بنا",
    footerCopyright: "جميع الحقوق محفوظة لمنصة Safi.io للذكاء العاطفي والمصالحة.",
    themeLight: "نهار ☀️",
    themeDark: "ليل 🌙",
    themeCandle: "شموع 🕯️",
    blogTitle: "مدونة التصالح والذكاء العاطفي 📚✍️",
    blogSubtitle: "مقالات ودراسات نفسية ممتعة لمساعدتك في تعزيز لغة الحوار وتجاوز أي خلاف رومانسية بذكاء وسلاسة تامة.",
    blogReadMore: "اقرأ المقال كاملاً 📖",
    blogBackMain: "العودة للواجهة الرئيسية (Safi.io)",
    blogBackList: "العودة لقائمة المقالات 📚",
    blogCtaTitle: "عندك خناقة وعايز تصالحها بطريقة مبتكرة؟ 🪄",
    blogCtaSubtitle: "ابني لها موقع مصالحة تفاعلي مخصص يحمل اسمها ورحلة حبكم في 10 ثوانٍ مجاناً!",
    blogCtaBtn: "ابدأ الآن واصنع رابط المصالحة 🚀",
    errorUpdateTitle: "عذراً، جاري تحديث خوادم المدونة 🛠️",
    errorUpdateDesc: "يمكنك قراءة جميع المقالات المميزة مباشرة من خلال تبويب المدونة الموجود في الصفحة الرئيسية للموقع.",
    errorDetailTitle: "المقال المطلوب غير متاح حالياً 📖",
    errorDetailDesc: "يمكنك تصفح بقية المقالات والدراسات العاطفية الممتعة من خلال الصفحة الرئيسية للمدونة.",
    demoModalTitle: "محاكاة رحلة المصالحة (10 ثوانٍ) ⚡",
    demoStationBadge: "المحطة",
    demoOf: "من",
    demoRunningText: "● جاري العرض السينمائي التلقائي السريع...",
    demoLaunchCta: "ابني صفحة مصالحة باسمها دلوقتي 🪄"
  },
  en: {
    dashboardTitle: "Secret Operations Dashboard 🔐",
    liveTracking: "Live Radar & Tracking",
    liveTrackingDesc: "Watch her exact progress instantly and send live push notifications or stealth whispers to her screen.",
    settingsTitle: "Experience & Content Settings",
    settingsDesc: "Tailor the messages, quiz questions, and automated courtroom to build a spectacular personalized apology.",
    saveChanges: "Save Magical Changes ✨",
    saving: "Saving Magic...",
    dangerZone: "Danger Zone",
    dangerZoneDesc: "Terminating the session will completely destroy the unique link, courtroom archives, and memory blocks.",
    deleteSiteBtn: "Terminate Link & Purge Session 🗑️",
    sendBtn: "Send Instant Whisper ⚡",
    sending: "Dispatching...",
    refresh: "Refresh Radar 🔄",
    noVisits: "Radar is silent.. No active visits yet 📡",
    noVisitsDesc: "The moment she opens her unique secret link, her screen coordinates and emotional responses will stream here.",
    landingSubtitle: "The absolute premium cinematic SaaS platform to playfully apologize and win her heart back with absolute elegance.",
    createMagicLink: "Create Her Magical Link Now 🪄",
    creating: "Crafting Surprise...",
    magicLinkReady: "✨ Surprise fully active! Copy her secret link and share it with her immediately:",
    copyLink: "Copy Secret Link 📋",
    copied: "Link Secured! 🚀",
    createLinkError: "Unable to instigate link. Please verify parameters and try again.",
    boyNameLabel: "Your Name (The Hero)",
    girlNameLabel: "Her Name (The Queen)",
    petNameLabel: "Her Favorite Pet Name",
    boyNamePlaceholder: "E.g. Ahmed / Alex...",
    girlNamePlaceholder: "E.g. Mariam / Sarah...",
    petNamePlaceholder: "E.g. Maryoma / Sweetie...",
    customSlugLabel: "Your Dedicated Unique Link Slug",
    customSlugPlaceholder: "ahmed-mariam",
    creatorEmailLabel: "Your Email Address (To receive the final pardon report & annual milestone reminders)",
    creatorEmailPlaceholder: "vip@example.com",
    pwdLabel: "Secret Passcode to Unlock Link (Crucial)",
    pwdPlaceholder: "Enter a distinctive passcode...",
    pwdHintLabel: "Passcode Hint",
    pwdHintPlaceholder: "E.g. Date of our first date / Where we met...",
    trustText: "100% Guaranteed | Absolute Privacy | Free Enterprise Trial",
    privacyNote: "🛡️ We NEVER ask for social media passwords or financial/banking credentials.",
    basicSettings: "Basics & Copy",
    quizSettings: "Questions & Quiz",
    courtSettings: "Courtroom & Rating",
    letterSettings: "Heartfelt Letter & Coupons",
    timeline: "Our Memories (Timeline)",
    addMemory: "Add New Milestone",
    trivia: "Memory Challenge (Trivia)",
    addQuestion: "Add Trap Question",
    coupons: "Gift Coupons",
    addCoupon: "Add Reward Coupon",
    letterBody: "Heartfelt Letter by Paragraph",
    addParagraph: "Add Emotional Paragraph",
    pwdReminder: "⚠️ Crucial: Do not forget to send her the secret passcode to unlock her journey!",
    telegramAlerts: "Live Radar (Telegram)",
    notificationsSettings: "Live Radar & Telegram Configurations",
    telegramSetup: "Steps to attach instant Telegram Radar streams:",
    telegramStep1: "1. Search for our official bot",
    telegramStep2: "2. Dispatch the command /start",
    telegramStep3: "3. Copy your unique Chat ID and securely insert it here",
    telegramOptional: "🔔 Enable Live Telegram Radar Streams (Optional)",
    telegramChatIdPlaceholder: "Telegram Chat ID (e.g. 123456789)",
    aiGenerator: "AI Experience Architect",
    aiTitle: "Magical AI Copy Architecture",
    aiDesc: "State the underlying incident reason and hit generate — our specialized AI will construct a magnificent cinematic apology complete with clever psychological quiz traps.",
    coreIntent: "Core Intent",
    textVibe: "Emotional Vibe",
    vibeIntensity: "Vibe Intensity",
    incidentReasonPlaceholder: "E.g. Forgot our anniversary / Was late to dinner...",
    generateMagic: "Instigate AI Magic ✨",
    journeyMap: "Journey Map",
    currentSectionLabel: "Active Station",
    lastActionLabel: "Last Interaction",
    deleteSession: "Purge Session",
    onlineNow: "Live Now 🟢",
    offline: "No Active Radar Streams",
    atGate: "Decrypted Gate 🔒",
    insidePlatform: "Exploring Platform 👑",
    disconnected: "Disconnected ⚪",
    broadcastPlaceholder: "Dispatch an instant stealth whisper to appear as a gentle popup on her screen...",
    navWall: "Anonymous Wall 🔒",
    navStories: "Apology Gallery 🏆",
    navGifts: "Gift Recommender 🎁",
    navCreate: "Instigate Apology Link 🪄",
    navBlog: "Emotional Blog 📚",
    demoBtn: "10s Cinematic Demo ⚡",
    loginBtn: "Access Radar 🔐",
    statsTitle: "Relationships Successfully Reconciled by Safi.io Engine:",
    liveBadge: "Streaming Live",
    adblockText: "Safi.io operates as a dedicated premium platform. Please disable AdBlock to sustain our computational servers 🤍",
    wallTitle: "Anonymous Apology Wall 🔒",
    wallSubtitle: "A 100% secure, encrypted sanctuary to post your unburdened heartfelt apologies to the universe without ever revealing your identity.",
    wallInputPlaceholder: "Inscribe your genuine, unburdened heartfelt apology here (Max 300 chars)...",
    wallSubmitBtn: "Inscribe Apology 🔒",
    wallEmpty: "Be the absolute first to inscribe an authentic apology onto the encrypted wall...",
    wallSuccessMsg: "Your heartfelt apology has been successfully etched onto the celestial wall! ✨",
    storiesTitle: "Hilarious & Clever Apology Gallery 🏆",
    storiesSubtitle: "The absolute most extraordinary, witty, and heartwarming couple reconciliation archives. Enjoy the entries and grant your vote (with a red heart ❤️) to the absolute best masterpiece!",
    voteBtn: "Upvote",
    votedBtn: "Upvoted",
    storiesPromptTitle: "Do you possess a witty reconciliation or funny couple dispute story? 💌",
    storiesPromptSubtitle: "Submit your masterpiece to our curators. We will feature it in next week's competition to win a VIP luxury coupon code!",
    giftsTitle: "Premium Tri-Zodiac Romantic Gift Recommender 🎁",
    giftsSubtitle: "Obtain highly intelligent, unconventional, highly tailored romantic gift recommendations engineered psychologically and astronomically according to your partner's exact age and zodiac sign!",
    giftsAgeLabel: "Select Her Active Age Bracket",
    giftsZodiacLabel: "Select Her Astronomical Zodiac Sign",
    giftsGenerateBtn: "Generate Premium Gift Recommendations ✨",
    giftsSuggestedTitle: "💡 Curated Luxury Recommender for Zodiac",
    giftsCallToAction: "Instigate a dedicated interactive apology website for her now and seal your reconciliation 🪄",
    loginModalTitle: "Access Secret Radar Room 🕵️",
    loginModalSubtitle: "Authenticate your link slug and master password to monitor her session instantly or calibrate the emotional engine.",
    loginSlugLabel: "Interactive Link Slug",
    loginPwdLabel: "Master Control Passcode",
    loginSubmitBtn: "Launch Secret Radar 🚀",
    loginErrorInvalid: "Invalid link slug or master passcode credentials.",
    loginErrorNetwork: "Server communication timeout. Please re-authenticate.",
    footerPrivacy: "Privacy Protocol",
    footerTerms: "Terms of Service",
    footerContact: "Secure Dispatch",
    footerCopyright: "Enterprise Copyright © Safi.io Platform. Engineered for ultimate couple reconciliation and lasting emotional warmth.",
    themeLight: "Solar ☀️",
    themeDark: "Midnight 🌙",
    themeCandle: "Candlelight 🕯️",
    blogTitle: "Emotional Intelligence & Reconciliation Blog 📚✍️",
    blogSubtitle: "Highly engaging psychological breakdowns and relationship manuals engineered to foster constructive couples dialogue and overcome romantic hurdles with utmost grace.",
    blogReadMore: "Explore Masterpiece 📖",
    blogBackMain: "Return to Main Portal (Safi.io)",
    blogBackList: "Return to Relationship Manuals 📚",
    blogCtaTitle: "Experiencing a romantic hurdle and wish to apologize beautifully? 🪄",
    blogCtaSubtitle: "Construct an incredibly elegant dedicated interactive reconciliation website carrying her name and love story in exactly 10 seconds for free!",
    blogCtaBtn: "Instigate Her Apology Link Now 🚀",
    errorUpdateTitle: "Pardon Our Dust: Curating Advanced Blog Servers 🛠️",
    errorUpdateDesc: "You may seamlessly explore all premium relationship manuals directly through the embedded Blog tab right on the main homepage portal.",
    errorDetailTitle: "The Requested Relationship Manual is Unavailable 📖",
    errorDetailDesc: "You may seamlessly continue browsing our deep emotional breakdowns and relationship guides from our main blog directory.",
    demoModalTitle: "Cinematic 10-Second Experience Simulation ⚡",
    demoStationBadge: "Station",
    demoOf: "of",
    demoRunningText: "● Automated rapid cinematic simulation in progress...",
    demoLaunchCta: "Construct Her Apology Link Immediately 🪄"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children, initialLocale = "ar" }) {
  const [locale, setLocale] = useState(initialLocale);

  // Synchronize HTML metadata
  useEffect(() => {
    document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = locale;
  }, [locale]);

  const t = useCallback((key) => {
    const activeGroup = translations[locale] || translations.ar;
    return activeGroup[key] || translations.ar[key] || key;
  }, [locale]);

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      locale: "ar",
      setLocale: () => {},
      t: (key) => translations.ar[key] || key
    };
  }
  return context;
}
